// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesjPEei1YZsBPAXecHmjNeW1iq0fDzGA',
    appId: '1:457521683491:web:f0ab2383500564b7176596',
    messagingSenderId: '457521683491',
    projectId: 'batch2307d-53443',
    authDomain: 'batch2307d-53443.firebaseapp.com',
    databaseURL: 'https://batch2307d-53443-default-rtdb.firebaseio.com',
    storageBucket: 'batch2307d-53443.firebasestorage.app',
    measurementId: 'G-1V5FMGD3D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IxanQpUHJsRS5cBAq-mVOzPYW7jJ0hw',
    appId: '1:457521683491:android:963f26d1b77c12c4176596',
    messagingSenderId: '457521683491',
    projectId: 'batch2307d-53443',
    databaseURL: 'https://batch2307d-53443-default-rtdb.firebaseio.com',
    storageBucket: 'batch2307d-53443.firebasestorage.app',
  );

}